C Copyright (c) 1978, Nicolae Ursu
C
C PROGRAMARE, INSTITUTUL POLITEHNIC CLUJ-NAPOCA, 1978
C Programul nr.1, pag. 132
C
C PROGRAM PT. TRANSFORMAREA UNUI UNGHI DIN RADIANI IN GRADE,MINUTE SI SECUNDE
      READ(*,*) PHIR
C   1 FORMAT(F10.6)
      PI=4.*ATAN(1.)
      PHIG=PHIR*180./PI
      IPHIG=PHIG
      PHIM=(PHIG-IPHIG)*60.
      MIN=PHIM
      SEC=(PHIM-MIN)*60.
      WRITE(*,2) PHIR,IPHIG,MIN,SEC
    2 FORMAT(///5X,F12.6,' RADIANI =',I6,' GRADE',I5,' MINUTE',F10.3,' 
     1SECUNDE'//)
      STOP
      END
